name: 3. Consultar Cliente

on:
  workflow_dispatch:
    inputs:
      nombre_cliente:
        description: 'Nombre del cliente a consultar'
        required: true

jobs:
  notificar_consulta:
    runs-on: ubuntu-latest
    steps:
      - name: 💬 Notificación de Acción
        run: |
          CLIENTE="${{ github.event.inputs.nombre_cliente }}"
          
          # Mensaje de aviso para el equipo
          echo "::notice title=CLIENTE CONSULTADO::[FLUJO 3] Se ha consultado la ficha de un cliente."
          echo "::notice title=CLIENTE CONSULTADO::Cliente Consultado: $CLIENTE"
          echo "::notice title=CLIENTE CONSULTADO::Usuario que consultó: ${{ github.actor }}"
          echo "Todos los miembros del equipo han sido notificados de esta consulta."
          
      - name: 💻 Simular Ejecución de Python
        # NOTA: Aquí iría la lógica real para llamar a tu clase ClienteManager.leer_cliente()
        run: |
          echo "Simulando ejecución de la función leer_cliente para $CLIENTE."
          echo "El contenido del archivo se leería."